# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{summon}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jim Benton"]
  s.date = %q{2009-08-25}
  s.description = %q{Allows for easily setting up deeply nested associations}
  s.email = %q{jim@autonomousmachine.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/summon.rb",
     "summon.gemspec",
     "test/summon_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/jim/summon}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.3}
  s.summary = %q{Provided a nice DSL for creating dummy data using Factory Girl factory definitions}
  s.test_files = [
    "test/summon_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thoughtbot-factory_girl>, [">= 1.2.0"])
    else
      s.add_dependency(%q<thoughtbot-factory_girl>, [">= 1.2.0"])
    end
  else
    s.add_dependency(%q<thoughtbot-factory_girl>, [">= 1.2.0"])
  end
end
